name: CI - Backend PortGO

on:
  push:
    paths:
      - 'api/**'
    branches:
      - main
  pull_request:
    paths:
      - 'api/**'

jobs:
  backend-ci:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: "sqlite:///./portgo.db"
      SECRET_KEY: "uma_chave_secreta_muito_forte_pode_ser_qualquer_coisa"
      ALGORITHM: "HS256"
      ACCESS_TOKEN_EXPIRE_MINUTES: 30

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Instalar dependências
        working-directory: ./api
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rodar seed para popular banco de dados
        working-directory: ./api
        run: python seed.py

      - name: Testar inicialização da API com Uvicorn
        working-directory: ./api
        run: |
          uvicorn main:app --host 127.0.0.1 --port 8001 --reload &
          sleep 5
          curl --fail http://127.0.0.1:8001/docs || (echo "Erro ao iniciar API" && exit 1)
